Add ::MIN and impl Default for ProbeEpoch and ProbeTicks types
auxoncorp/modality-probe pull request #229
Opened 2020-09-10 20:33 UTC by mullr

2020-09-10 20:36 UTC, jonlamb-gh approved these changes

2020-09-11 20:52 UTC, nathanaschbacher commented
This still needs more discussion according to @mullr

2020-09-11 20:54 UTC, nathanaschbacher requested changes
@mullr tells me that this actually needs more discussion, so I'm marking that with a request for changes... namely more discussion.

2020-09-15 15:25 UTC, pittma commented
This is subsumed in #242 by https://github.com/auxoncorp/modality-probe/pull/242/commits/c29560907307eba1411370b92c296225896ed77f.

2020-09-15 15:25 UTC, closed without merging