cli: exclude internal events in graph output by default
auxoncorp/modality-probe pull request #255
Opened 2020-09-28 17:53 UTC by pittma

This PR adds the `--include-internal-events` switch to the `export` sub-command. By default, these are now excluded.

---

Closes #235.

2020-09-28 20:23 UTC, jonlamb-gh approved these changes

2020-09-29 18:49 UTC, jonlamb-gh commented
I noticed an issue today running `export` over this [log.jsonl](https://github.com/auxoncorp/modality-probe/files/5301234/trace_log.txt). It looks like we're missing some arrows when `--include-internal-events` is omitted.

With internal events:
![cyclic_with_internals](https://user-images.githubusercontent.com/1671674/94602447-b9529f80-0249-11eb-9e10-caa65ebaf4e3.png)

Without internal events:
![cyclic_without_internals](https://user-images.githubusercontent.com/1671674/94602466-bf488080-0249-11eb-85cd-2808ad7f3630.png)

2020-09-29 18:52 UTC, jonlamb-gh requested changes
Can you look into the missing arrows issue?

2020-09-29 18:58 UTC, pittma commented
@jonlamb-gh I'm having a hard time seeing what's missing…

2020-09-30 19:49 UTC, pittma commented
![screen_2020-09-30-12-48-23](https://user-images.githubusercontent.com/1194436/94732603-5598a700-031b-11eb-89de-37cd9c355e5b.png)

2020-09-30 20:18 UTC, jonlamb-gh approved these changes

2020-09-30 21:45 UTC, merged